consumer:
  playlistartisthits:
    cover:
      create:
        enable: true
        queue: teste_queue_create
        dlq: teste_queue_create_dlq
        routing-key: teste_queue_create_rky
        exchange: teste_queue_create_exc
        consumers:
          min: 2
          max: 9
