spring:
  config:
    import: 
      - optional:classpath:job/playlist-artist-hits/cover/br.yml
      - optional:classpath:job/playlist-artist-hits/cover/others.yml
      - optional:classpath:job/playlist-artist-hits/cover/default.yml