description: recommendationManager >> PlaylistArtistHits
spring:
  config:
    import: 
    - optional:job/playlist-artist-hits/cover/br.yml
    - optional:job/playlist-artist-hits/cover/others.yml
    - optional:job/playlist-artist-hits/cover/default.yml