consumers:
  playlist-artist-hits-cover:
    name: Consumer playlistArtistHits - Cover
    create-cover:
      enable: true
      queue-id: recommendation_playlistArtistHits_cover_create
      queue-name: recommendation_playlistArtistHits_cover_create
      consumers:
        min: 1
        max: 5
